# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushPullNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushPullNative
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  

  platform :ios, '9.0'
  target 'PushPullNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PushPullNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushPullNative-tvOS

  target 'PushPullNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
